'use client';

import { useEffect, useMemo, useState } from 'react';

const EMPTY = { values: [], goals: [], tasks: [], quads: { q1: [], q2: [], q3: [], q4: [] }, synced: 0 };
const LOCAL_KEY = 'priorityos.localState';
const today = () => new Date().toISOString().split('T')[0];
const pad = (v) => String(v).padStart(2, '0');
const localDateTime = (d) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:00`;
const addMin = (s, m) => { const d = new Date(s); d.setMinutes(d.getMinutes() + m); return localDateTime(d); };
const recLabel = (r) => !r ? 'Once' : r.includes('BYDAY=MO,TU,WE,TH,FR') ? 'Weekdays' : r.includes('DAILY') ? 'Daily' : r.includes('WEEKLY') ? 'Weekly' : r.includes('MONTHLY') ? 'Monthly' : r;
const norm = (s) => ({ values: Array.isArray(s?.values) ? s.values : [], goals: Array.isArray(s?.goals) ? s.goals : [], tasks: Array.isArray(s?.tasks) ? s.tasks : [], quads: { q1: Array.isArray(s?.quads?.q1) ? s.quads.q1 : [], q2: Array.isArray(s?.quads?.q2) ? s.quads.q2 : [], q3: Array.isArray(s?.quads?.q3) ? s.quads.q3 : [], q4: Array.isArray(s?.quads?.q4) ? s.quads.q4 : [] }, synced: Number.isFinite(Number(s?.synced)) ? Number(s.synced) : 0 });

export default function Home() {
  const [phase, setPhase] = useState('deciding');
  const [state, setState] = useState(EMPTY);
  const [auth, setAuth] = useState({ loading: true, connected: false, profile: null });
  const [taskType, setTaskType] = useState('op');
  const [recRule, setRecRule] = useState('RRULE:FREQ=DAILY');
  const [syncing, setSyncing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [toasts, setToasts] = useState([]);
  const synced = useMemo(() => state.tasks.filter((t) => t.eventId).length, [state.tasks]);

  useEffect(() => { (async () => {
    try {
      const a = await fetch('/api/auth/status', { cache: 'no-store' }).then((r) => r.json());
      setAuth({ loading: false, connected: !!a.connected, profile: a.profile || null });
      if (a.connected) {
        const s = await fetch('/api/state', { cache: 'no-store' }).then((r) => r.ok ? r.json() : { state: EMPTY });
        setState(norm(s.state));
      } else {
        const local = localStorage.getItem(LOCAL_KEY); if (local) setState(norm(JSON.parse(local)));
      }
      const p = new URLSearchParams(location.search);
      if (p.get('auth') === 'connected') notify('success', 'Google Calendar connected', 'Blob saving and calendar sync are ready.');
      if (p.get('auth') === 'failed') notify('error', 'Google connection failed', 'Check OAuth credentials and redirect URI.');
      if (p.has('auth')) history.replaceState({}, document.title, '/');
    } catch { setAuth({ loading: false, connected: false, profile: null }); }
  })(); }, []);

  function notify(type, title, msg) { const id = crypto.randomUUID?.() || String(Date.now()); setToasts((x) => [...x, { id, type, title, msg, show: true }]); setTimeout(() => { setToasts((x) => x.map((t) => t.id === id ? { ...t, show: false } : t)); setTimeout(() => setToasts((x) => x.filter((t) => t.id !== id)), 400); }, 4500); }
  function go(p) { setPhase(p); document.getElementById('app')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  async function persist(next) { const clean = norm({ ...next, synced: next.tasks.filter((t) => t.eventId).length }); setState(clean); if (!auth.connected) { localStorage.setItem(LOCAL_KEY, JSON.stringify(clean)); return; } setSaving(true); try { const r = await fetch('/api/state', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ state: clean }) }); if (!r.ok) throw new Error((await r.json()).error || 'Blob save failed.'); } catch (e) { notify('error', 'Blob save failed', e.message); } finally { setSaving(false); } }
  function addList(kind, id) { const el = document.getElementById(id); const v = el.value.trim(); if (!v) return; el.value = ''; persist({ ...state, [kind]: [...state[kind], v] }); }
  function delList(kind, i) { persist({ ...state, [kind]: state[kind].filter((_, x) => x !== i) }); }
  function buildTask(name) { const tz = Intl.DateTimeFormat().resolvedOptions().timeZone; const id = crypto.randomUUID?.() || String(Date.now()); if (taskType === 'op') { const date = document.getElementById('op-date').value || today(); const time = document.getElementById('op-time').value || '09:00'; const dur = Number.parseInt(document.getElementById('op-dur').value, 10) || 60; const start = `${date}T${time}:00`; return { id, name, type: 'op', recRule, start, end: addMin(start, dur), tz, eventId: null, calLink: null, quadrant: null }; } const date = document.getElementById('pr-date').value || today(); const startT = document.getElementById('pr-start').value || '09:00'; const endT = document.getElementById('pr-end').value || '10:00'; const dur = Number.parseInt(document.getElementById('pr-dur').value, 10); const start = `${date}T${startT}:00`; return { id, name, type: 'pr', start, end: Number.isFinite(dur) && dur > 0 ? addMin(start, dur) : `${date}T${endT}:00`, tz, eventId: null, calLink: null, quadrant: null }; }
  async function addTask() { const el = document.getElementById('t-inp'); const name = el.value.trim(); if (!name) return notify('error', 'Missing task name', 'Please enter a task description.'); if (!auth.connected) return notify('error', 'Calendar not connected', 'Connect Google Calendar first.'); setSyncing(true); try { const task = buildTask(name); const r = await fetch('/api/calendar/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ task, context: { goals: state.goals, values: state.values } }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Calendar sync failed.'); el.value = ''; await persist({ ...state, tasks: [...state.tasks, { ...task, eventId: data.eventId, calLink: data.link }] }); notify('success', 'Synced to Google Calendar', `"${name}" is on your calendar.`); } catch (e) { notify('error', 'Calendar sync failed', e.message); } finally { setSyncing(false); } }
  async function delTask(i) { const task = state.tasks[i]; const tasks = state.tasks.filter((_, x) => x !== i); const quads = Object.fromEntries(['q1','q2','q3','q4'].map((q) => [q, state.quads[q].filter((n) => n !== task?.name)])); if (task?.eventId && auth.connected) fetch('/api/calendar/events', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ eventId: task.eventId }) }).catch(() => null); await persist({ ...state, tasks, quads }); }
  async function assignQ() { const idx = Number.parseInt(document.getElementById('del-sel').value, 10); if (Number.isNaN(idx) || !state.tasks[idx]) return; const u = document.getElementById('del-urg').value; const im = document.getElementById('del-imp').value; const q = u === 'urgent' && im === 'important' ? 'q1' : u === 'not-urgent' && im === 'important' ? 'q2' : u === 'urgent' ? 'q3' : 'q4'; const tasks = state.tasks.map((t, i) => i === idx ? { ...t, quadrant: q } : t); const quads = Object.fromEntries(['q1','q2','q3','q4'].map((k) => [k, tasks.filter((t) => t.quadrant === k).map((t) => t.name)])); await persist({ ...state, tasks, quads }); const task = tasks[idx]; if (task.eventId && auth.connected) fetch('/api/calendar/events', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ task, context: { goals: state.goals, values: state.values } }) }).catch(() => notify('error', 'Priority label not synced', 'Calendar event update failed.')); }
  async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); location.reload(); }

  const unassigned = state.tasks.map((task, index) => ({ task, index })).filter(({ task }) => !task.quadrant);

  return <>
    <nav><a className="logo" href="#"><div className="logo-icon">P</div><span className="logo-name">PriorityOS</span></a><div className="nav-r"><div className={`cal-status ${auth.connected ? 'connected' : 'disconnected'}`}><div className="cal-dot" />{auth.loading ? 'Checking Google Calendar…' : auth.connected ? 'Google Calendar connected' : 'Google Calendar not connected'}</div>{auth.connected ? <button className="btn-ghost" onClick={logout}>Disconnect</button> : <a className="btn-cal" href="/api/auth/google">Connect Calendar</a>}</div></nav>
    <section className="hero"><div className="hero-bg" /><div className="hero-content"><div className="tag-pill lg"><span className="tag-new">Live</span><span className="tag-txt">Google Calendar sync — Decide · Do · Deliver</span></div><h1 className="hero-h1">Your Priorities.<br />Your <span className="serif">Calendar.</span></h1><p className="hero-sub">Add tasks once. Operational work recurs automatically. Project tasks land on exact dates. Everything synced live to Google Calendar.</p><button className="hero-cta" onClick={() => document.getElementById('app')?.scrollIntoView({ behavior: 'smooth' })}>Open Priority Manager</button></div><div className="dash-wrap"><div className="dash-mock"><div className="dash-bar"><div className="d-dot" style={{background:'#ff5f57'}}/><div className="d-dot" style={{background:'#febc2e'}}/><div className="d-dot" style={{background:'#28c840'}}/><span className="dash-bar-txt">PriorityOS — Calendar Sync View</span><span style={{marginLeft:'auto',fontSize:10,color:'var(--green)',fontWeight:600}}>{saving ? '● SAVING' : '● LIVE'}</span></div><div className="dash-grid"><Stat label="GOALS" value={state.goals.length} color="green" sub="SMART objectives"/><Stat label="TASKS" value={state.tasks.length} color="blue" sub="In pipeline"/><Stat label="SYNCED" value={synced} color="amber" sub="On Google Calendar"/><Stat label="DO IT NOW" value={state.quads.q1.length} color="red" sub="Urgent & important"/></div></div></div><div className="hero-fade" /></section>
    <main id="app" className="main"><div className="stats"><SmallStat label="Values" value={state.values.length} color="green"/><SmallStat label="Goals" value={state.goals.length} color="blue"/><SmallStat label="Tasks" value={state.tasks.length} color="amber"/><SmallStat label="Synced to Calendar" value={synced} color="green"/></div><div className="sync-note"><strong>Storage:</strong> connected users save to Vercel Blob under their Google account. {auth.connected ? `Signed in as ${auth.profile?.email}.` : 'Connect Google Calendar to enable cloud saving and calendar sync. Until then, this uses local browser storage.'}</div><div className="ptabs"><Tab p="deciding" n="1" phase={phase} go={go}>Deciding</Tab><Tab p="doing" n="2" phase={phase} go={go}>Doing</Tab><Tab p="delivering" n="3" phase={phase} go={go}>Delivering</Tab></div>
      <section className={`psec ${phase === 'deciding' ? 'active' : ''}`}><Header color="green" tag="Phase 1 — Transformation" title={<>Who are you? What do you <span className="serif">value?</span></>} sub="Define your values and roles first. Then write SMART goals aligned to that foundation."/><div className="card"><div className="card-hdr">Values, Mission & Roles</div><div className="irow"><input id="v-inp" placeholder="e.g. Family, Financial freedom, Health, Creativity…" onKeyDown={(e)=>e.key==='Enter'&&addList('values','v-inp')}/><button className="btn" onClick={()=>addList('values','v-inp')}>Add</button></div><List items={state.values} empty="No values yet — what truly matters to you?" color="green" del={(i)=>delList('values',i)}/></div><div className="card"><div className="card-hdr">SMART Goals & Objectives</div><div className="smart">{['Specific','Measurable','Attainable','Relevant','Trackable'].map((x)=><div className="sm-cell" key={x}><div className="sm-l">{x[0]}</div><div className="sm-w">{x}</div></div>)}</div><textarea id="g-inp" placeholder="e.g. Publish 2 articles/month by Q3 to grow audience by 30%"/><div style={{marginTop:9}}><button className="btn btn-full" onClick={()=>addList('goals','g-inp')}>Add SMART Goal</button></div><div style={{marginTop:12}}><List items={state.goals} empty="No goals yet — use the SMART criteria above." color="blue" del={(i)=>delList('goals',i)}/></div></div><div className="nav-row"><span/><button className="btn" onClick={()=>go('doing')}>Continue to Doing →</button></div></section>
      <section className={`psec ${phase === 'doing' ? 'active' : ''}`}><Header color="blue" tag="Phase 2 — Performance" title={<>Plan your work.<br/><span className="serif">Act on your plans.</span></>} sub="Classify each task as Operational (recurring) or Project (specific date). Then schedule it directly to Google Calendar."/><div className="cmp"><Compare kind="ops" title="Operational Work" rows={[['Nature','Independent'],['Planning','Usually simple'],['Duration','Ongoing'],['Output','Repetitive'],['Calendar','Recurring event']]}/><Compare kind="prj" title="Project" rows={[['Nature','Dependent'],['Planning','Often complex'],['Duration','Temporary'],['Output','Unique'],['Calendar','Specific date']]}/></div><div className="card"><div className="card-hdr">Add Task + Schedule to Google Calendar</div><div className="irow"><input id="t-inp" placeholder="Describe your task or activity…"/></div><div className="ttog"><button className={`ttbtn ${taskType==='op'?'op':''}`} onClick={()=>setTaskType('op')}>Operational (recurring)</button><button className={`ttbtn ${taskType==='pr'?'pr':''}`} onClick={()=>setTaskType('pr')}>Project (specific date)</button></div>{taskType==='op'?<div><div className="field-lbl">Recurrence</div><div className="rec-opts">{[['Daily','RRULE:FREQ=DAILY'],['Weekly','RRULE:FREQ=WEEKLY'],['Monthly','RRULE:FREQ=MONTHLY'],['Weekdays','RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR']].map(([l,r])=><button key={r} className={`rec-btn ${recRule===r?'active':''}`} onClick={()=>setRecRule(r)}>{l}</button>)}</div><div className="g2" style={{marginBottom:10}}><div><div className="field-lbl">Start date</div><input type="date" id="op-date" defaultValue={today()}/></div><div><div className="field-lbl">Time</div><input type="time" id="op-time" defaultValue="09:00"/></div></div><div><div className="field-lbl">Duration (minutes)</div><input id="op-dur" defaultValue="60"/></div></div>:<div><div className="g2" style={{marginBottom:10}}><div><div className="field-lbl">Date</div><input type="date" id="pr-date" defaultValue={today()}/></div><div><div className="field-lbl">Start time</div><input type="time" id="pr-start" defaultValue="09:00"/></div></div><div className="g2"><div><div className="field-lbl">End time</div><input type="time" id="pr-end" defaultValue="10:00"/></div><div><div className="field-lbl">Duration (min, auto)</div><input id="pr-dur" placeholder="or set end time above"/></div></div></div>}<div style={{marginTop:12}}><button className="btn-cal btn-full" onClick={addTask} disabled={syncing || !auth.connected} style={{justifyContent:'center'}}>{syncing ? <><span className="spin"/> Syncing to Google Calendar…</> : 'Add Task & Sync to Google Calendar'}</button></div><Tasks tasks={state.tasks} del={delTask}/></div><div className="nav-row"><button className="btn-ghost" onClick={()=>go('deciding')}>← Back to Deciding</button><button className="btn" onClick={()=>go('delivering')}>Continue to Delivering →</button></div></section>
      <section className={`psec ${phase === 'delivering' ? 'active' : ''}`}><Header color="amber" tag="Phase 3 — Accountability" title={<>Deliver and <span className="serif">commit.</span></>} sub="Use the Eisenhower Matrix to prioritize. Tasks assigned here also get a priority label on your calendar event."/><div className="card"><div className="card-hdr">Assign Task to Priority Quadrant</div><div style={{marginBottom:10}}><div className="field-lbl">Task</div><select id="del-sel" disabled={!unassigned.length}>{unassigned.length ? unassigned.map(({task,index})=><option key={task.id} value={index}>{task.name}</option>) : <option>No unassigned tasks — add tasks in Phase 2</option>}</select></div><div className="g2" style={{marginBottom:12}}><div><div className="field-lbl">Urgency</div><select id="del-urg"><option value="urgent">Urgent</option><option value="not-urgent">Not urgent</option></select></div><div><div className="field-lbl">Importance</div><select id="del-imp"><option value="important">Important</option><option value="not-important">Not important</option></select></div></div><button className="btn btn-full" onClick={assignQ} disabled={!unassigned.length}>Assign to Matrix</button></div><div className="mx-hdrs"><div className="mx-hdr" style={{color:'var(--green)'}}>URGENT</div><div className="mx-hdr" style={{color:'var(--blue)'}}>NOT URGENT</div></div><div className="mx"><Quad id="q1" t="Do It Now" e="Important + Urgent" items={state.quads.q1}/><Quad id="q2" t="Schedule It" e="Important + Not Urgent" items={state.quads.q2}/><Quad id="q3" t="Delegate It" e="Not Important + Urgent" items={state.quads.q3}/><Quad id="q4" t="Delete It" e="Not Important + Not Urgent" items={state.quads.q4}/></div><div className="hint"><h4>Q2 Focus — The Rewarding Investment Quadrant</h4><p>Deliberately schedule Q2 tasks — important but not urgent. These build your future without screaming for attention. Plan them or they'll never happen.</p><ul><li>Plan before you delegate — think how the team can help</li><li>Assign to the best person, not just the closest</li><li>Communicate expectations in writing with agreed dates</li><li>Follow up and evaluate using consistent tools</li></ul></div><div className="nav-row"><button className="btn-ghost" onClick={()=>go('doing')}>← Back to Doing</button></div></section>
    </main><div className="toast-wrap">{toasts.map((t)=><div key={t.id} className={`toast ${t.type} ${t.show?'show':''}`}><span className="toast-icon">{t.type==='success'?'✓':'✕'}</span><div><div className="toast-title">{t.title}</div><div className="toast-msg">{t.msg}</div></div></div>)}</div>
  </>;
}
function Stat({label,value,color,sub}){return <div className="ds"><div className="ds-lbl">{label}</div><div className="ds-val" style={{color:`var(--${color})`}}>{value}</div><div className="ds-sub">{sub}</div></div>}
function SmallStat({label,value,color}){return <div className="sc"><div className="sc-n" style={{color:`var(--${color})`}}>{value}</div><div className="sc-l">{label}</div></div>}
function Tab({p,n,phase,go,children}){return <button className={`ptab p${n} ${phase===p?'active':''}`} onClick={()=>go(p)}><span className="pn">Phase {n}</span>{children}</button>}
function Header({color,tag,title,sub}){return <><div className="sh-tag lg" style={{color:`var(--${color})`}}><span className="sh-dot" style={{background:`var(--${color})`}}/>{tag}</div><h2 className="sh-title">{title}</h2><p className="sh-sub">{sub}</p></>}
function List({items,empty,color,del}){return <ul className="ilist">{items.length?items.map((x,i)=><li key={`${x}-${i}`}><span className="idot" style={{background:`var(--${color})`}}/><span style={{flex:1}}>{x}</span><button className="del" onClick={()=>del(i)}>×</button></li>):<li className="empty">{empty}</li>}</ul>}
function Compare({kind,title,rows}){return <div className={`cmp-col ${kind}`}><h4>{title}</h4>{rows.map(([k,v])=><div className="cr" key={k}><span className="ck">{k}</span><span className="cv">{v}</span></div>)}</div>}
function Tasks({tasks,del}){return <ul className="ilist" style={{marginTop:14}}>{tasks.length?tasks.map((t,i)=><li key={t.id||`${t.name}-${i}`}><span className="idot" style={{background:`var(--${t.type==='op'?'blue':'amber'})`}}/><span style={{flex:1}}><span style={{display:'block',marginBottom:3}}>{t.name}</span><span style={{fontSize:11,color:'var(--muted)'}}>{t.type==='op'?`🔄 ${recLabel(t.recRule)}`:`📅 ${t.start.slice(0,10)}`}</span></span><span className={`tag ${t.type}`} style={{marginRight:6}}>{t.type==='op'?'Operational':'Project'}</span>{t.eventId?<span className="tag synced">✓ Synced</span>:null}{t.calLink?<a href={t.calLink} target="_blank" rel="noreferrer" style={{marginLeft:6,color:'var(--blue)',fontSize:11,textDecoration:'none'}}>↗</a>:null}<button className="del" onClick={()=>del(i)}>×</button></li>):<li className="empty">No tasks yet — add above to sync to your calendar.</li>}</ul>}
function Quad({id,t,e,items}){return <div className={`qd ${id}`}><div className="qey">{e}</div><div className="qnm">{t}</div><ul className="qi">{items.length?items.map((x,i)=><li key={`${x}-${i}`}><span style={{fontSize:9,flexShrink:0}}>▸</span>{x}</li>):<li className="qe">Empty</li>}</ul></div>}
