'use client';

import { useEffect, useMemo, useState } from 'react';

const EMPTY={values:[],goals:[],tasks:[],quads:{q1:[],q2:[],q3:[],q4:[]},synced:0};
const LOCAL='priorityos.localState';
const WEEKDAYS=[['MO','Mon'],['TU','Tue'],['WE','Wed'],['TH','Thu'],['FR','Fri'],['SA','Sat'],['SU','Sun']];
const WEEKDAY_VALUES=['MO','TU','WE','TH','FR'];
const today=()=>new Date().toISOString().slice(0,10);
const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};
const pad=v=>String(v).padStart(2,'0');
const localDT=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:00`;
const addMin=(s,m)=>{const d=new Date(s);d.setMinutes(d.getMinutes()+m);return localDT(d)};
const qLabel=q=>({q1:'Do It Now',q2:'Investment',q3:'Delegate It',q4:'Delete It'}[q]||'Needs priority');
const recLabel=r=>!r?'Once':r.includes('BYDAY=MO,TU,WE,TH,FR')?'Weekdays':r.includes('BYDAY=')?`Weekly on ${r.split('BYDAY=')[1]}`:r.includes('DAILY')?'Daily':r.includes('MONTHLY')?'Monthly':r.includes('WEEKLY')?'Weekly':r;
const norm=s=>({values:Array.isArray(s?.values)?s.values:[],goals:Array.isArray(s?.goals)?s.goals:[],tasks:Array.isArray(s?.tasks)?s.tasks:[],quads:{q1:Array.isArray(s?.quads?.q1)?s.quads.q1:[],q2:Array.isArray(s?.quads?.q2)?s.quads.q2:[],q3:Array.isArray(s?.quads?.q3)?s.quads.q3:[],q4:Array.isArray(s?.quads?.q4)?s.quads.q4:[]},synced:Number.isFinite(Number(s?.synced))?Number(s.synced):0});

export default function PriorityAppV3(){
 const [phase,setPhase]=useState('deciding'),[state,setState]=useState(EMPTY),[auth,setAuth]=useState({loading:true,connected:false,profile:null}),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState(false),[toasts,setToasts]=useState([]);
 const [scheduleType,setScheduleType]=useState('op'),[recurrenceType,setRecurrenceType]=useState('daily'),[weeklyDays,setWeeklyDays]=useState(['MO']);
 const synced=useMemo(()=>state.tasks.filter(t=>t.eventId).length,[state.tasks]);
 const unassigned=state.tasks.map((task,index)=>({task,index})).filter(x=>!x.task.quadrant);
 const scheduleCandidates=state.tasks.map((task,index)=>({task,index})).filter(x=>x.task.quadrant&&!x.task.eventId);
 const isWeekdays=recurrenceType==='weekly'&&WEEKDAY_VALUES.every(d=>weeklyDays.includes(d))&&weeklyDays.length===5;
 useEffect(()=>{(async()=>{try{const a=await fetch('/api/auth/status',{cache:'no-store'}).then(r=>r.json());setAuth({loading:false,connected:!!a.connected,profile:a.profile||null});if(a.connected){const s=await fetch('/api/state',{cache:'no-store'}).then(r=>r.ok?r.json():{state:EMPTY});setState(norm(s.state));}else{const local=localStorage.getItem(LOCAL);if(local)setState(norm(JSON.parse(local)));}const p=new URLSearchParams(location.search);if(p.get('auth')==='connected')toast('success','Google Calendar connected','Blob saving and calendar sync are ready.');if(p.get('auth')==='failed')toast('error','Google connection failed','Check OAuth credentials and redirect URI.');if(p.has('auth'))history.replaceState({},document.title,'/');}catch{setAuth({loading:false,connected:false,profile:null})}})()},[]);
 function toast(type,title,msg){const id=crypto.randomUUID?.()||String(Date.now());setToasts(x=>[...x,{id,type,title,msg,show:true}]);setTimeout(()=>{setToasts(x=>x.map(t=>t.id===id?{...t,show:false}:t));setTimeout(()=>setToasts(x=>x.filter(t=>t.id!==id)),400)},4500)}
 function go(p){setPhase(p);document.getElementById('app')?.scrollIntoView({behavior:'smooth',block:'start'})}
 async function persist(next){const clean=norm({...next,synced:next.tasks.filter(t=>t.eventId).length});setState(clean);if(!auth.connected){localStorage.setItem(LOCAL,JSON.stringify(clean));return}setSaving(true);try{const r=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:clean})});if(!r.ok)throw new Error((await r.json()).error||'Blob save failed.')}catch(e){toast('error','Blob save failed',e.message)}finally{setSaving(false)}}
 function addList(kind,id){const el=document.getElementById(id),v=el.value.trim();if(!v)return;el.value='';persist({...state,[kind]:[...state[kind],v]})}
 function delList(kind,i){persist({...state,[kind]:state[kind].filter((_,x)=>x!==i)})}
 function quads(tasks){return Object.fromEntries(['q1','q2','q3','q4'].map(q=>[q,tasks.filter(t=>t.quadrant===q).map(t=>t.name)]))}
 function addTask(){const el=document.getElementById('t-inp'),name=el.value.trim();if(!name)return toast('error','Missing task name','Please enter a task description.');el.value='';persist({...state,tasks:[...state.tasks,{id:crypto.randomUUID?.()||String(Date.now()),name,type:null,recRule:null,start:null,end:null,tz:Intl.DateTimeFormat().resolvedOptions().timeZone,eventId:null,calLink:null,quadrant:null}]});toast('success','Task captured','Assign it to the matrix before scheduling.')}
 async function delTask(i){const task=state.tasks[i],tasks=state.tasks.filter((_,x)=>x!==i);if(task?.eventId&&auth.connected)fetch('/api/calendar/events',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:task.eventId})}).catch(()=>null);await persist({...state,tasks,quads:quads(tasks)})}
 async function assignQ(){const i=Number.parseInt(document.getElementById('del-sel').value,10);if(Number.isNaN(i)||!state.tasks[i])return;const u=document.getElementById('del-urg').value,im=document.getElementById('del-imp').value,q=u==='urgent'&&im==='important'?'q1':u==='not-urgent'&&im==='important'?'q2':u==='urgent'?'q3':'q4';const tasks=state.tasks.map((t,x)=>x===i?{...t,quadrant:q}:t);await persist({...state,tasks,quads:quads(tasks)});toast('success',`Assigned to ${qLabel(q)}`,q==='q1'?'Q1 tasks must be scheduled today or tomorrow.':'This task can now be scheduled freely.')}
 function setPreset(type){if(type==='weekdays'){setRecurrenceType('weekly');setWeeklyDays(WEEKDAY_VALUES);return}setRecurrenceType(type)}
 function makeRule(){if(recurrenceType==='daily')return 'RRULE:FREQ=DAILY';if(recurrenceType==='monthly')return 'RRULE:FREQ=MONTHLY';if(recurrenceType==='weekly'){if(!weeklyDays.length)throw new Error('Choose at least one weekday for weekly recurrence.');return `RRULE:FREQ=WEEKLY;BYDAY=${weeklyDays.join(',')}`}return 'RRULE:FREQ=DAILY'}
 function buildTask(base){const tz=Intl.DateTimeFormat().resolvedOptions().timeZone;if(scheduleType==='op'){const date=document.getElementById('sch-op-date').value||today(),time=document.getElementById('sch-op-time').value||'09:00',dur=Number.parseInt(document.getElementById('sch-op-dur').value,10)||60,start=`${date}T${time}:00`;return {...base,type:'op',recRule:makeRule(),start,end:addMin(start,dur),tz}}const date=document.getElementById('sch-pr-date').value||today(),st=document.getElementById('sch-pr-start').value||'09:00',et=document.getElementById('sch-pr-end').value||'10:00',dur=Number.parseInt(document.getElementById('sch-pr-dur').value,10),start=`${date}T${st}:00`;return {...base,type:'pr',recRule:null,start,end:Number.isFinite(dur)&&dur>0?addMin(start,dur):`${date}T${et}:00`,tz}}
 async function scheduleTask(){const i=Number.parseInt(document.getElementById('sch-task-sel').value,10);if(Number.isNaN(i)||!state.tasks[i])return toast('error','Choose a task','Select a prioritized task to schedule.');if(!auth.connected)return toast('error','Calendar not connected','Connect Google Calendar first.');const base=state.tasks[i];let task;try{task=buildTask(base)}catch(e){return toast('error','Recurrence needs details',e.message)}const d=task.start?.slice(0,10);if(base.quadrant==='q1'&&d!==today()&&d!==tomorrow())return toast('error','Q1 scheduling rule','Urgent + important tasks must be scheduled for today or tomorrow.');setSyncing(true);try{const r=await fetch('/api/calendar/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task,context:{goals:state.goals,values:state.values}})}),data=await r.json();if(!r.ok)throw new Error(data.error||'Calendar sync failed.');const tasks=state.tasks.map((t,x)=>x===i?{...task,eventId:data.eventId,calLink:data.link}:t);await persist({...state,tasks});toast('success','Scheduled to Google Calendar',`"${task.name}" is now scheduled.`)}catch(e){toast('error','Calendar sync failed',e.message)}finally{setSyncing(false)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.reload()}
 return <><Nav auth={auth} logout={logout}/><Hero saving={saving} state={state} synced={synced}/><main id="app" className="main"><Stats state={state} synced={synced}/><div className="sync-note"><strong>Storage:</strong> connected users save to Vercel Blob under their Google account. {auth.connected?`Signed in as ${auth.profile?.email}.`:'Connect Google Calendar to enable cloud saving and calendar sync. Until then, this uses local browser storage.'}</div><div className="ptabs"><Tab p="deciding" n="1" phase={phase} go={go}>Deciding</Tab><Tab p="doing" n="2" phase={phase} go={go}>Doing</Tab><Tab p="delivering" n="3" phase={phase} go={go}>Delivering</Tab></div><Deciding active={phase==='deciding'} go={go} state={state} addList={addList} delList={delList}/><Doing active={phase==='doing'} go={go} state={state} addTask={addTask} delTask={delTask}/><Delivering active={phase==='delivering'} go={go} state={state} unassigned={unassigned} candidates={scheduleCandidates} assignQ={assignQ} scheduleTask={scheduleTask} auth={auth} syncing={syncing} scheduleType={scheduleType} setScheduleType={setScheduleType} recurrenceType={recurrenceType} weeklyDays={weeklyDays} setWeeklyDays={setWeeklyDays} setPreset={setPreset} isWeekdays={isWeekdays}/></main><Toasts toasts={toasts}/></>}
function Nav({auth,logout}){return <nav><a className="logo" href="#"><div className="logo-icon">P</div><span className="logo-name">PriorityOS</span></a><div className="nav-r"><div className={`cal-status ${auth.connected?'connected':'disconnected'}`}><div className="cal-dot"/>{auth.loading?'Checking Google Calendar…':auth.connected?'Google Calendar connected':'Google Calendar not connected'}</div>{auth.connected?<button className="btn-ghost" onClick={logout}>Disconnect</button>:<a className="btn-cal" href="/api/auth/google">Connect Calendar</a>}</div></nav>}
function Hero({saving,state,synced}){return <section className="hero"><div className="hero-bg"/><div className="hero-content"><div className="tag-pill lg"><span className="tag-new">Live</span><span className="tag-txt">Prioritize first, then schedule to Google Calendar</span></div><h1 className="hero-h1">Your Priorities.<br/>Your <span className="serif">Calendar.</span></h1><p className="hero-sub">Capture work in Phase 2. Decide what it means in Phase 3. Then schedule it with rules that keep the calendar beast polite.</p><button className="hero-cta" onClick={()=>document.getElementById('app')?.scrollIntoView({behavior:'smooth'})}>Open Priority Manager</button></div><div className="dash-wrap"><div className="dash-mock"><div className="dash-bar"><div className="d-dot" style={{background:'#ff5f57'}}/><div className="d-dot" style={{background:'#febc2e'}}/><div className="d-dot" style={{background:'#28c840'}}/><span className="dash-bar-txt">PriorityOS — Calendar Sync View</span><span style={{marginLeft:'auto',fontSize:10,color:'var(--green)',fontWeight:600}}>{saving?'● SAVING':'● LIVE'}</span></div><div className="dash-grid"><Stat label="GOALS" value={state.goals.length} color="green" sub="SMART objectives"/><Stat label="TASKS" value={state.tasks.length} color="blue" sub="In pipeline"/><Stat label="SYNCED" value={synced} color="amber" sub="On Google Calendar"/><Stat label="DO IT NOW" value={state.quads.q1.length} color="red" sub="Urgent & important"/></div></div></div><div className="hero-fade"/></section>}
function Stats({state,synced}){return <div className="stats"><SmallStat label="Values" value={state.values.length} color="green"/><SmallStat label="Goals" value={state.goals.length} color="blue"/><SmallStat label="Tasks" value={state.tasks.length} color="amber"/><SmallStat label="Synced to Calendar" value={synced} color="green"/></div>}
function Deciding({active,go,state,addList,delList}){return <section className={`psec ${active?'active':''}`}><Header color="green" tag="Phase 1 — Transformation" title={<>Who are you? What do you <span className="serif">value?</span></>} sub="Define your values and roles first. Then write SMART goals aligned to that foundation."/><div className="card"><div className="card-hdr">Values, Mission & Roles</div><div className="irow"><input id="v-inp" placeholder="e.g. Family, Financial freedom, Health, Creativity…" onKeyDown={e=>e.key==='Enter'&&addList('values','v-inp')}/><button className="btn" onClick={()=>addList('values','v-inp')}>Add</button></div><List items={state.values} empty="No values yet." color="green" del={i=>delList('values',i)}/></div><div className="card"><div className="card-hdr">SMART Goals & Objectives</div><div className="smart">{['Specific','Measurable','Attainable','Relevant','Trackable'].map(x=><div className="sm-cell" key={x}><div className="sm-l">{x[0]}</div><div className="sm-w">{x}</div></div>)}</div><textarea id="g-inp" placeholder="e.g. Publish 2 articles/month by Q3 to grow audience by 30%"/><div style={{marginTop:9}}><button className="btn btn-full" onClick={()=>addList('goals','g-inp')}>Add SMART Goal</button></div><div style={{marginTop:12}}><List items={state.goals} empty="No goals yet." color="blue" del={i=>delList('goals',i)}/></div></div><div className="nav-row"><span/><button className="btn" onClick={()=>go('doing')}>Continue to Doing →</button></div></section>}
function Doing({active,go,state,addTask,delTask}){return <section className={`psec ${active?'active':''}`}><Header color="blue" tag="Phase 2 — Performance" title={<>Capture your work.<br/><span className="serif">Prepare to prioritize.</span></>} sub="Phase 2 is your intake lane. Add the task first, then decide its quadrant and schedule it in Phase 3."/><div className="cmp"><Compare kind="ops" title="Operational Work" rows={[[ 'Nature','Independent' ],[ 'Planning','Usually simple' ],[ 'Duration','Ongoing' ],[ 'Calendar','After priority' ]]}/><Compare kind="prj" title="Project" rows={[[ 'Nature','Dependent' ],[ 'Planning','Often complex' ],[ 'Duration','Temporary' ],[ 'Calendar','After priority' ]]}/></div><div className="card"><div className="card-hdr">Add Task to Priority Queue</div><div className="irow"><input id="t-inp" placeholder="Describe your task or activity…" onKeyDown={e=>e.key==='Enter'&&addTask()}/><button className="btn" onClick={addTask}>Add Task</button></div><Tasks tasks={state.tasks} del={delTask}/></div><div className="nav-row"><button className="btn-ghost" onClick={()=>go('deciding')}>← Back to Deciding</button><button className="btn" onClick={()=>go('delivering')}>Continue to Delivering →</button></div></section>}
function Delivering(p){return <section className={`psec ${p.active?'active':''}`}><Header color="amber" tag="Phase 3 — Accountability" title={<>Decide, then <span className="serif">schedule.</span></>} sub="Assign each task to the Eisenhower Matrix first. Only then schedule it to Google Calendar. Q1 tasks must land today or tomorrow."/><div className="card"><div className="card-hdr">Assign Task to Priority Quadrant</div><div style={{marginBottom:10}}><div className="field-lbl">Task</div><select id="del-sel" disabled={!p.unassigned.length}>{p.unassigned.length?p.unassigned.map(({task,index})=><option key={task.id} value={index}>{task.name}</option>):<option>No unassigned tasks yet</option>}</select></div><div className="g2" style={{marginBottom:12}}><div><div className="field-lbl">Urgency</div><select id="del-urg"><option value="urgent">Urgent</option><option value="not-urgent">Not urgent</option></select></div><div><div className="field-lbl">Importance</div><select id="del-imp"><option value="important">Important</option><option value="not-important">Not important</option></select></div></div><button className="btn btn-full" onClick={p.assignQ} disabled={!p.unassigned.length}>Assign to Matrix</button></div><div className="mx-hdrs"><div className="mx-hdr" style={{color:'var(--green)'}}>URGENT</div><div className="mx-hdr" style={{color:'var(--blue)'}}>NOT URGENT</div></div><div className="mx"><Quad id="q1" t="Do It Now" e="Important + Urgent" items={p.state.quads.q1}/><Quad id="q2" t="Investment" e="Important + Not Urgent" items={p.state.quads.q2}/><Quad id="q3" t="Delegate It" e="Not Important + Urgent" items={p.state.quads.q3}/><Quad id="q4" t="Delete It" e="Not Important + Not Urgent" items={p.state.quads.q4}/></div><ScheduleCard {...p}/><div className="hint"><h4>Q1 Rule + Q2 Focus</h4><p>Urgent and important tasks must be scheduled today or tomorrow. Everything else can be scheduled freely once the priority decision is clear.</p><ul><li>Weekdays is now Monday through Friday recurrence</li><li>Monthly repeats monthly from the selected start date</li><li>Q2 investment work should get a deliberate calendar block</li></ul></div><div className="nav-row"><button className="btn-ghost" onClick={()=>p.go('doing')}>← Back to Doing</button></div></section>}
function ScheduleCard(p){return <div className="card" style={{marginTop:16}}><div className="card-hdr">Schedule Prioritized Task to Google Calendar</div><div style={{marginBottom:10}}><div className="field-lbl">Prioritized task</div><select id="sch-task-sel" disabled={!p.candidates.length}>{p.candidates.length?p.candidates.map(({task,index})=><option key={task.id} value={index}>{task.name} — {qLabel(task.quadrant)}</option>):<option>Assign a task to the matrix first</option>}</select></div><div className="ttog"><button className={`ttbtn ${p.scheduleType==='op'?'op':''}`} onClick={()=>p.setScheduleType('op')}>Operational (recurring)</button><button className={`ttbtn ${p.scheduleType==='pr'?'pr':''}`} onClick={()=>p.setScheduleType('pr')}>Project (specific date)</button></div>{p.scheduleType==='op'?<Operational {...p}/>:<Project/>}<div style={{marginTop:12}}><button className="btn-cal btn-full" onClick={p.scheduleTask} disabled={p.syncing||!p.auth.connected||!p.candidates.length} style={{justifyContent:'center'}}>{p.syncing?<><span className="spin"/> Syncing to Google Calendar…</>:'Schedule Task & Sync to Google Calendar'}</button></div><p className="sh-sub" style={{margin:'12px 0 0'}}>Q1 tasks can only be scheduled today or tomorrow. All other quadrants are open-schedule.</p></div>}
function Operational({recurrenceType,setPreset,weeklyDays,setWeeklyDays,isWeekdays}){const toggle=d=>setWeeklyDays(weeklyDays.includes(d)?weeklyDays.filter(x=>x!==d):[...weeklyDays,d]);return <div><div className="field-lbl">Recurrence</div><div className="rec-opts"><button className={`rec-btn ${recurrenceType==='daily'?'active':''}`} onClick={()=>setPreset('daily')}>Daily</button><button className={`rec-btn ${recurrenceType==='weekly'&&!isWeekdays?'active':''}`} onClick={()=>setPreset('weekly')}>Weekly</button><button className={`rec-btn ${recurrenceType==='monthly'?'active':''}`} onClick={()=>setPreset('monthly')}>Monthly</button><button className={`rec-btn ${isWeekdays?'active':''}`} onClick={()=>setPreset('weekdays')}>Weekdays</button></div>{recurrenceType==='weekly'?<div style={{marginBottom:10}}><div className="field-lbl">Specific weekdays</div><div className="rec-opts">{WEEKDAYS.map(([v,l])=><button key={v} className={`rec-btn ${weeklyDays.includes(v)?'active':''}`} onClick={()=>toggle(v)}>{l}</button>)}</div></div>:null}<div className="g2" style={{marginBottom:10}}><div><div className="field-lbl">Start date</div><input type="date" id="sch-op-date" defaultValue={today()}/></div><div><div className="field-lbl">Time</div><input type="time" id="sch-op-time" defaultValue="09:00"/></div></div><div><div className="field-lbl">Duration (minutes)</div><input id="sch-op-dur" defaultValue="60"/></div></div>}
function Project(){return <div><div className="g2" style={{marginBottom:10}}><div><div className="field-lbl">Date</div><input type="date" id="sch-pr-date" defaultValue={today()}/></div><div><div className="field-lbl">Start time</div><input type="time" id="sch-pr-start" defaultValue="09:00"/></div></div><div className="g2"><div><div className="field-lbl">End time</div><input type="time" id="sch-pr-end" defaultValue="10:00"/></div><div><div className="field-lbl">Duration (min, auto)</div><input id="sch-pr-dur" placeholder="or set end time above"/></div></div></div>}
function Stat({label,value,color,sub}){return <div className="ds"><div className="ds-lbl">{label}</div><div className="ds-val" style={{color:`var(--${color})`}}>{value}</div><div className="ds-sub">{sub}</div></div>}
function SmallStat({label,value,color}){return <div className="sc"><div className="sc-n" style={{color:`var(--${color})`}}>{value}</div><div className="sc-l">{label}</div></div>}
function Tab({p,n,phase,go,children}){return <button className={`ptab p${n} ${phase===p?'active':''}`} onClick={()=>go(p)}><span className="pn">Phase {n}</span>{children}</button>}
function Header({color,tag,title,sub}){return <><div className="sh-tag lg" style={{color:`var(--${color})`}}><span className="sh-dot" style={{background:`var(--${color})`}}/>{tag}</div><h2 className="sh-title">{title}</h2><p className="sh-sub">{sub}</p></>}
function List({items,empty,color,del}){return <ul className="ilist">{items.length?items.map((x,i)=><li key={`${x}-${i}`}><span className="idot" style={{background:`var(--${color})`}}/><span style={{flex:1}}>{x}</span><button className="del" onClick={()=>del(i)}>×</button></li>):<li className="empty">{empty}</li>}</ul>}
function Compare({kind,title,rows}){return <div className={`cmp-col ${kind}`}><h4>{title}</h4>{rows.map(([k,v])=><div className="cr" key={k}><span className="ck">{k}</span><span className="cv">{v}</span></div>)}</div>}
function Tasks({tasks,del}){return <ul className="ilist" style={{marginTop:14}}>{tasks.length?tasks.map((t,i)=><li key={t.id||`${t.name}-${i}`}><span className="idot" style={{background:`var(--${t.quadrant==='q1'?'red':t.quadrant?'amber':'blue'})`}}/><span style={{flex:1}}><span style={{display:'block',marginBottom:3}}>{t.name}</span><span style={{fontSize:11,color:'var(--muted)'}}>{t.eventId?`${t.type==='op'?'🔄 '+recLabel(t.recRule):'📅 '+t.start.slice(0,10)}`:t.quadrant?`⚡ ${qLabel(t.quadrant)} — ready to schedule`:'Needs matrix assignment'}</span></span>{t.quadrant?<span className="tag pr" style={{marginRight:6}}>{qLabel(t.quadrant)}</span>:null}{t.type?<span className={`tag ${t.type}`} style={{marginRight:6}}>{t.type==='op'?'Operational':'Project'}</span>:null}{t.eventId?<span className="tag synced">✓ Synced</span>:null}{t.calLink?<a href={t.calLink} target="_blank" rel="noreferrer" style={{marginLeft:6,color:'var(--blue)',fontSize:11,textDecoration:'none'}}>↗</a>:null}<button className="del" onClick={()=>del(i)}>×</button></li>):<li className="empty">No tasks yet — add work in Phase 2.</li>}</ul>}
function Quad({id,t,e,items}){return <div className={`qd ${id}`}><div className="qey">{e}</div><div className="qnm">{t}</div><ul className="qi">{items.length?items.map((x,i)=><li key={`${x}-${i}`}><span style={{fontSize:9,flexShrink:0}}>▸</span>{x}</li>):<li className="qe">Empty</li>}</ul></div>}
function Toasts({toasts}){return <div className="toast-wrap">{toasts.map(t=><div key={t.id} className={`toast ${t.type} ${t.show?'show':''}`}><span className="toast-icon">{t.type==='success'?'✓':'✕'}</span><div><div className="toast-title">{t.title}</div><div className="toast-msg">{t.msg}</div></div></div>)}</div>}
