'use client';
import {useEffect,useMemo,useState} from 'react';
import DashboardCalendarPanel from './DashboardCalendarPanel';
import StatisticsPanel from './StatisticsPanel';
import HabitsPanel from './HabitsPanel';
import CanvasPanel from './CanvasPanel';
import WorkboardDashboard from './WorkboardDashboard';

const EMPTY={values:[],goals:[],tasks:[],calendarEvents:[],statistics:null,habits:{completions:{}},canvas:null,quads:{q1:[],q2:[],q3:[],q4:[]},synced:0};
const nav=[['dashboard','▦','Dashboard'],['canvas','⬚','Canvas'],['calendar','◴','Calendar'],['statistics','▧','Statistics'],['habits','◎','Habits'],['privacy','◌','Privacy'],['terms','□','Terms']];
const habitsShape=h=>({completions:h?.completions&&typeof h.completions==='object'?h.completions:{}});
function norm(s){return{values:Array.isArray(s?.values)?s.values:[],goals:Array.isArray(s?.goals)?s.goals:[],tasks:Array.isArray(s?.tasks)?s.tasks:[],calendarEvents:Array.isArray(s?.calendarEvents)?s.calendarEvents:[],statistics:s?.statistics&&typeof s.statistics==='object'?s.statistics:null,habits:habitsShape(s?.habits),canvas:s?.canvas&&typeof s.canvas==='object'?s.canvas:null,quads:{q1:Array.isArray(s?.quads?.q1)?s.quads.q1:[],q2:Array.isArray(s?.quads?.q2)?s.quads.q2:[],q3:Array.isArray(s?.quads?.q3)?s.quads.q3:[],q4:Array.isArray(s?.quads?.q4)?s.quads.q4:[]},synced:Number(s?.synced)||0}}
function initial(k,d){if(typeof window==='undefined')return d;return new URLSearchParams(location.search).get(k)||d}
function isRecurring(t){return !!(t?.recRule||t?.type==='op')}
function habitOverall(tasks,habits){let due=0,done=0,end=new Date();end.setHours(0,0,0,0);let start=new Date(end);start.setDate(start.getDate()-27);for(const t of tasks.filter(isRecurring)){for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){let key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,c=habits?.completions?.[t.id]?.[key];if(c==='skipped')continue;due++;if(c==='done')done++}}return due?Math.round(done/due*100):0}
function title(v){return{dashboard:'Dashboard',canvas:'Canvas',calendar:'Calendar',statistics:'Statistics',habits:'Habits',privacy:'Privacy',terms:'Terms'}[v]||'Dashboard'}

export default function DashboardClientIntegrated(){
 const[mode,setMode]=useState('business'),[view,setViewState]=useState('dashboard'),[menuOpen,setMenuOpen]=useState(false),[syncing,setSyncing]=useState(false),[auth,setAuth]=useState({loading:true,connected:false,profile:null}),[state,setState]=useState(EMPTY),[loading,setLoading]=useState(true);
 const events=state.calendarEvents||[],habitCount=state.tasks.filter(isRecurring).length,habitScore=habitOverall(state.tasks,state.habits),next=useMemo(()=>events.filter(e=>e.start).slice().sort((a,b)=>new Date(a.start)-new Date(b.start))[0],[events]);
 useEffect(()=>{const m=initial('mode',localStorage.getItem('priorityos.mode')==='personal'?'personal':'business'),v=initial('view','dashboard');setMode(m==='personal'?'personal':'business');setViewState(nav.some(x=>x[0]===v)?v:'dashboard');load(m)},[]);
 async function load(m){setLoading(true);try{const a=await fetch('/api/auth/status',{cache:'no-store'}).then(r=>r.json());setAuth({loading:false,connected:!!a.connected,profile:a.profile||null});if(!a.connected)return;const s=await fetch(`/api/state?mode=${m}&t=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():{state:EMPTY});setState(norm(s.state))}finally{setLoading(false)}}
 async function saveWorkspace(nextState){const clean=norm(nextState);setState(clean);const r=await fetch(`/api/state?mode=${mode}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,state:clean})});if(!r.ok)throw new Error('Workspace save failed.');const data=await r.json().catch(()=>({state:clean}));setState(norm(data.state||clean))}
 async function importGoogleEvents(){setSyncing(true);try{const r=await fetch(`/api/google/import-events?mode=${mode}`,{method:'POST',cache:'no-store'});const data=await r.json().catch(()=>({}));if(data.requiresReconnect&&data.reconnectUrl){window.location.href=data.reconnectUrl;return;}if(!r.ok)throw new Error(data.error||'Google Calendar import failed.');setState(norm(data.state));}catch(error){alert(error.message||'Google Calendar import failed.')}finally{setSyncing(false)}}
 const saveStatistics=statistics=>saveWorkspace({...state,statistics});
 const saveHabits=habits=>saveWorkspace({...state,habits});
 const saveCanvas=canvas=>saveWorkspace({...state,canvas});
 function setView(v){setViewState(v);setMenuOpen(false);history.replaceState({},'',`/dashboard?mode=${mode}&view=${v}`)}
 function switchMode(m){localStorage.setItem('priorityos.mode',m);setMode(m);history.replaceState({},'',`/dashboard?mode=${m}&view=${view}`);load(m)}
 if(!auth.loading&&!auth.connected)return <main className="main" style={{paddingTop:130}}><section className="card"><h1 className="sh-title">Connect to open your <span className="serif">dashboard.</span></h1><p className="sh-sub">Create your PriorityOS account to save dashboards, canvas boards, habits, charts, and calendar events.</p><a className="btn-cal" href="/api/auth/google?returnTo=/dashboard">Create Account</a></section></main>;
 return <main className="dash-full-shell"><header className="dash-menu-top"><div className="dash-menu-left"><button className="hamb" onClick={()=>setMenuOpen(!menuOpen)}>☰</button><div className="brand-mini"><div className="logo-icon">P</div><strong>PriorityOS</strong></div>{menuOpen&&<div className="hamb-menu">{nav.map(([k,i,l])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k)}><span>{i}</span>{l}</button>)}</div>}</div><div className="dash-title-block"><h1>{title(view)}</h1><p>{mode==='business'?'Business':'Personal'} command center</p></div><div className="dash-search wide">⌕ <span>Search priorities, canvas, habits, statistics...</span></div><button className="btn-ghost google-import-btn" onClick={importGoogleEvents} disabled={syncing}>{syncing?'Syncing Google...':'Sync Google Events'}</button><a className="btn-cal" href={`/dashboard/planner?mode=${mode}`}>Launch Guided Planner</a><div className="ttog dash-mode">{['business','personal'].map(m=><button key={m} className={`ttbtn ${mode===m?(m==='business'?'op':'pr'):''}`} onClick={()=>switchMode(m)}>{m[0].toUpperCase()+m.slice(1)}</button>)}</div><div className="dash-profile"><div className="logo-icon">{auth.profile?.email?.[0]?.toUpperCase()||'P'}</div><span>{auth.profile?.email?.split('@')[0]||'Account'}</span></div></header><section className="dash-page-full">{view==='dashboard'&&<WorkboardDashboard s={state} events={events} next={next} loading={loading} setView={setView} habitScore={habitScore} habitCount={habitCount} mode={mode}/>} {view==='canvas'&&<CanvasPanel canvas={state.canvas} onSave={saveCanvas}/>} {view==='calendar'&&<DashboardCalendarPanel mode={mode} events={events} setView={setView}/>} {view==='statistics'&&<StatisticsPanel statistics={state.statistics} onSave={saveStatistics}/>} {view==='habits'&&<HabitsPanel tasks={state.tasks} habits={state.habits} onSave={saveHabits} setView={setView}/>} {view==='privacy'&&<Legal title="Privacy Policy"/>} {view==='terms'&&<Legal title="Terms of Service" terms/>}</section></main>
}
function Legal({title,terms}){return <section className="dash-panel legal-native"><h2>{title}</h2><p>{terms?'These terms govern use of PriorityOS and its planning, canvas, calendar, habit tracking, charting, and account features.':'PriorityOS stores your account workspace, canvas boards, task data, habit completions, statistics charts, and calendar events to provide your dashboard experience.'}</p><p>Data is organized by account and workspace. Google Calendar sync is optional and only used when you connect and schedule externally.</p></section>}
