'use client';
import {useRef,useState,useEffect} from 'react';

const qNames={q1:'Do It Now',q2:'Investment',q3:'Delegate It',q4:'Delete It'};
const qColors={q1:'green',q2:'blue',q3:'amber',q4:'red'};
const qLabels={q1:'Do It Now',q2:'Investment',q3:'Delegate It',q4:'Delete It'};
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function time(v){try{return new Date(v).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}catch{return''}}
function fdate(v){try{return new Date(v).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}catch{return v||'Not scheduled'}}
function eventOnDay(event,day){if(!event?.start)return false;const s=new Date(event.start),d=new Date(`${day}T00:00:00`);if(iso(s)===day)return true;if(!event.recRule)return false;if(d<new Date(s.getFullYear(),s.getMonth(),s.getDate()))return false;if(event.recRule.includes('FREQ=DAILY'))return true;if(event.recRule.includes('FREQ=MONTHLY'))return d.getDate()===s.getDate();if(event.recRule.includes('FREQ=WEEKLY')){const by=event.recRule.match(/BYDAY=([^;]+)/)?.[1],map=['SU','MO','TU','WE','TH','FR','SA'];return by?by.split(',').includes(map[d.getDay()]):d.getDay()===s.getDay()}return false}
function isRecurring(t){return !!(t?.recRule||t?.type==='op')}

export default function WorkboardDashboard({s,statistics,events,next,loading,setView,habitScore,habitCount,mode,addQuickAction,dailyNotes,saveDailyNotes}){
 const wrap=useRef(null),drag=useRef(null),widthRef=useRef(45);
 const[width,setWidth]=useState(45),[selectedDay,setSelectedDay]=useState(iso(new Date())),[quickAction,setQuickAction]=useState(''),[quickQuadrant,setQuickQuadrant]=useState('q1'),[quickSaving,setQuickSaving]=useState(false);
 useEffect(()=>{widthRef.current=width},[width]);
 useEffect(()=>{function move(e){if(!drag.current||!wrap.current)return;const rect=wrap.current.getBoundingClientRect();setWidth(Math.max(28,Math.min(72,((e.clientX-rect.left)/rect.width)*100)))}function up(){drag.current=null;document.body.classList.remove('resizing')}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[]);
 function start(){drag.current=true;document.body.classList.add('resizing')}
 async function submitQuickAction(e){e.preventDefault();if(!quickAction.trim()||quickSaving)return;setQuickSaving(true);try{await addQuickAction(quickAction,quickQuadrant);setQuickAction('')}catch(error){alert(error.message||'Could not add action.')}finally{setQuickSaving(false)}}
 const dayEvents=(events||[]).filter(e=>eventOnDay(e,selectedDay)).sort((a,b)=>new Date(a.start)-new Date(b.start));
 const charts=Array.isArray(statistics?.charts)?statistics.charts:[];
 const pinned=charts.find(c=>c.id===statistics?.pinnedChartId);
 const showcase=pinned||charts.at(-1)||{name:'Your Statistic',metric:'Create a statistic',cadence:'weekly',values:[],dates:[]};
 return <div className="workboard-wrap">
  <PinnedStatistic chart={showcase} pinned={!!pinned} setView={setView}/>
  <section ref={wrap} className="workboard" style={{gridTemplateColumns:`minmax(230px,${width}fr) 9px minmax(320px,${100-width}fr)`}}>
   <TaskPane s={s} habitScore={habitScore} habitCount={habitCount} setView={setView} mode={mode} quickAction={quickAction} setQuickAction={setQuickAction} quickQuadrant={quickQuadrant} setQuickQuadrant={setQuickQuadrant} submitQuickAction={submitQuickAction} quickSaving={quickSaving}/>
   <div className="pane-resizer" onPointerDown={start}/>
   <DayPane events={dayEvents} selected={selectedDay} setSelected={setSelectedDay} next={next} loading={loading} setView={setView} dailyNotes={dailyNotes} saveDailyNotes={saveDailyNotes}/>
  </section>
 </div>
}
function PinnedStatistic({chart,pinned,setView}){const values=Array.isArray(chart?.values)?chart.values.map(Number).filter(Number.isFinite):[];const max=Math.max(...values,1),min=Math.min(...values,0),range=Math.max(max-min,1),w=1000,h=210,pad=28;const pts=values.map((v,i)=>({x:values.length===1?w/2:pad+(i/(values.length-1))*(w-pad*2),y:h-pad-((v-min)/range)*(h-pad*2)}));const path=pts.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');return <section className="pinned-stat-card"><div className="pinned-stat-head"><div><span className="pane-kicker">Pinned Statistic</span><h2>{chart.name}</h2><p>{chart.metric} · {chart.cadence}</p></div><div className="pinned-stat-actions"><span className="pinned-stat-badge">{pinned?'Pinned':'Latest chart'}</span><button className="pane-action" onClick={()=>setView('statistics')}>Open Statistics</button></div></div><div className="pinned-stat-chart"><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><line x1={pad} y1={h-pad} x2={w-pad} y2={h-pad} stroke="rgba(255,255,255,.12)"/><line x1={pad} y1={h/2} x2={w-pad} y2={h/2} stroke="rgba(255,255,255,.07)"/>{path?<path d={path} fill="none" stroke="var(--blue)" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/>:null}{pts.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="4" fill="var(--blue)"/>)}</svg></div><div className="pinned-stat-footer"><strong>{values.length?values.at(-1).toLocaleString():'—'}</strong><span>{values.length?'Latest value':'Create a chart in Statistics to start tracking a metric'}</span></div></section>}
function TaskPane({s,habitScore,habitCount,setView,mode,quickAction,setQuickAction,quickQuadrant,setQuickQuadrant,submitQuickAction,quickSaving}){const tasks=s.tasks||[],q1=tasks.filter(t=>t.quadrant==='q1'),q2=tasks.filter(t=>t.quadrant==='q2'),ops=tasks.filter(isRecurring),loose=tasks.filter(t=>!t.quadrant&&!isRecurring(t));return <article className="workspace-pane task-pane"><PaneHead kicker="Today" title="Quick Action"/><form className="quick-action-card" onSubmit={submitQuickAction}><input value={quickAction} onChange={e=>setQuickAction(e.target.value)} placeholder="What action will move today forward?"/><div className="quick-matrix">{Object.entries(qLabels).map(([q,label])=><button type="button" key={q} className={`quick-matrix-btn ${q} ${quickQuadrant===q?'active':''}`} onClick={()=>setQuickQuadrant(q)}>{label}</button>)}</div><button className="btn-cal quick-action-submit" type="submit" disabled={!quickAction.trim()||quickSaving}>{quickSaving?'Saving…':'Add today’s action'}</button></form><PaneHead kicker="Inbox" title="Tasks & Checklist" action="Plan" href={`/dashboard/planner?mode=${mode}`}/><TaskSection title="Do It Now" color="green" items={q1}/><TaskSection title="Investment" color="blue" items={q2}/><TaskSection title="Operational Habits" color="amber" items={ops}/>{loose.length?<TaskSection title="Unsorted" color="red" items={loose}/>:null}<div className="pane-mini-card"><strong>{habitScore}% consistency</strong><span>{habitCount} recurring task{habitCount===1?'':'s'} tracked.</span><button onClick={()=>setView('habits')}>Open Habits</button></div></article>}
function TaskSection({title,color,items}){return <div className="task-sec"><div className="task-sec-head"><span className={`dot ${color}`}/><strong>{title}</strong><em>{items.length}</em></div>{items.length?items.slice(0,8).map((t,i)=><label className="check-row" key={t.id||`${title}-${i}`}><input type="checkbox" readOnly checked={false}/><span>{t.name||t.title||t}</span>{isRecurring(t)?<b>recurs</b>:null}</label>):<p className="empty">Nothing here yet.</p>}</div>}
function DayPane({events,selected,setSelected,next,loading,setView,dailyNotes,saveDailyNotes}){const d=new Date(`${selected}T12:00:00`),hours=Array.from({length:15},(_,i)=>i+6);function shift(n){const x=new Date(`${selected}T12:00:00`);x.setDate(x.getDate()+n);setSelected(iso(x))}return <article className="workspace-pane day-pane"><div className="pane-head day-head"><div><span className="pane-kicker">Specific Day</span><h2>{d.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}</h2></div><div className="day-controls"><button onClick={()=>shift(-1)}>‹</button><button onClick={()=>setSelected(iso(new Date()))}>Today</button><button onClick={()=>shift(1)}>›</button><input type="date" value={selected} onChange={e=>setSelected(e.target.value)}/></div></div>{loading?<p className="empty">Loading calendar...</p>:<div className="day-timeline">{hours.map(h=>{const slot=events.filter(e=>new Date(e.start).getHours()===h);return <div className="hour-row" key={h}><span>{formatHour(h)}</span><div>{slot.length?slot.map(e=><div key={`${e.id}-${e.start}`} className={`event-pill ${qColors[e.quadrant]||'blue'}`}><strong>{e.title}</strong><em>{time(e.start)} · {qNames[e.quadrant]||'PriorityOS'}</em></div>):null}</div></div>})}</div>}<DailyNotesCard date={selected} dailyNotes={dailyNotes} saveDailyNotes={saveDailyNotes}/><div className="pane-mini-card next-card"><strong>{next?.title||'No next commitment'}</strong><span>{next?fdate(next.start):'Use the planner to schedule one.'}</span><button onClick={()=>setView('calendar')}>Open Month Calendar</button></div></article>}
function DailyNotesCard({date,dailyNotes,saveDailyNotes}){const saved=dailyNotes?.[date]||{};const [mindDump,setMindDump]=useState(saved.mindDump||'');const [sourceSignals,setSourceSignals]=useState(saved.sourceSignals||'');const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false);useEffect(()=>{const next=dailyNotes?.[date]||{};setMindDump(next.mindDump||'');setSourceSignals(next.sourceSignals||'');setDirty(false)},[date,dailyNotes]);async function save(){setSaving(true);try{await saveDailyNotes(date,{mindDump,sourceSignals});setDirty(false)}finally{setSaving(false)}}return <section className="daily-notes-card"><div className="daily-notes-head"><div><span className="pane-kicker">Daily Notes</span><h3>{new Date(`${date}T12:00:00`).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}</h3></div>{dirty?<span className="daily-notes-dirty">Unsaved</span>:<span className="daily-notes-saved">Saved</span>}</div><label><span>Mind Dump</span><textarea value={mindDump} onChange={e=>{setMindDump(e.target.value);setDirty(true)}} placeholder="Anything on your mind. Clear the mental backlog here..." /></label><label><span>Source Signals</span><textarea value={sourceSignals} onChange={e=>{setSourceSignals(e.target.value);setDirty(true)}} placeholder="Signals, observations, ideas, and patterns worth noticing..." /></label><button className="btn-cal quick-action-submit" onClick={save} disabled={saving||!dirty}>{saving?'Saving…':'Save notes'}</button></section>}
function formatHour(h){const suffix=h>=12?'PM':'AM',hr=h%12||12;return `${hr} ${suffix}`}
function PaneHead({kicker,title,action,href,onClick}){return <div className="pane-head"><div><span className="pane-kicker">{kicker}</span><h2>{title}</h2></div>{href?<a className="pane-action" href={href}>{action}</a>:action?<button className="pane-action" onClick={onClick}>{action}</button>:null}</div>}
